const EVENTS = {
  SERVER_ADD: "SERVER::ADD",
  CONNECT: "connect",
  FAIL: "SERVER::FAIL",
  SERVER_KILL: "SERVER::KILL",
  SERVER_LIST: "SERVER::LIST",
  SERVER_REMOVE: "SERVER::REMOVE",
  SERVER_RESTART: "SERVER::RESTART",
  SERVER_START: "SERVER::START",
  SUCCESS: "SERVER::SUCCESS"
};

module.exports = {
  EVENTS
};
