const EVENTS = {
  IPC: {
    CONNECT: "connect",
    MESSAGE: "IPC::GENERIC_MESSAGE"
  },
  HONO: {
    START: "HONO::START",
    STOP: "HONO::STOP",
    RESTART: "HONO::RESTART"
  },
  SERVER: {
    SERVER_ADD: "SERVER::ADD",
    SERVER_KILL: "SERVER::KILL",
    SERVER_LIST: "SERVER::LIST",
    SERVER_REMOVE: "SERVER::REMOVE",
    SERVER_RESTART: "SERVER::RESTART",
    SERVER_START: "SERVER::START",
  },
  STATUS: {
    FAIL: "STATUS::FAIL",
    SUCCESS: "STATUS::SUCCESS"
  }
};

module.exports = {
  EVENTS
};
